import pandas as pd
from utils.data_processor import profile_data
import io

def generate_html_report(df, insights=None):
    """
    Generates an HTML report for the dataset.
    """
    profile = profile_data(df)

    html = f"""
    <html>
    <head>
        <title>Data Analysis Report</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 40px; }}
            h1 {{ color: #2c3e50; }}
            h2 {{ color: #34495e; border-bottom: 2px solid #ecf0f1; padding-bottom: 10px; }}
            .metric {{ background: #f8f9fa; padding: 10px; margin: 5px; border-radius: 5px; display: inline-block; }}
            table {{ border-collapse: collapse; width: 100%; margin-top: 20px; }}
            th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
            th {{ background-color: #f2f2f2; }}
        </style>
    </head>
    <body>
        <h1>Data Analysis Report</h1>
        <p>Generated by AI Data Analyst</p>

        <h2>Dataset Overview</h2>
        <div class="metric"><b>Rows:</b> {profile['rows']}</div>
        <div class="metric"><b>Columns:</b> {profile['columns']}</div>
        <div class="metric"><b>Duplicates:</b> {profile['duplicates']}</div>
        <div class="metric"><b>Missing Values:</b> {profile['missing_total']}</div>

        <h2>AI Insights</h2>
        <div style="background-color: #e8f4f8; padding: 20px; border-radius: 10px;">
            {insights if insights else "No AI insights generated."}
        </div>

        <h2>Data Sample</h2>
        {df.head(10).to_html(classes='table')}

        <h2>Numerical Statistics</h2>
        {pd.DataFrame(profile['numeric_stats']).to_html(classes='table') if profile['numeric_stats'] else "No numeric columns."}

    </body>
    </html>
    """
    return html
